<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="AVIRVERM-M-L7GK" failures="1" tests="4" name="Surefire test" time="11.895" errors="0" timestamp="2022-07-01T17:55:59 IST">
  <testcase classname="testCases.secondTest" name="first" time="0.002"/>
  <testcase classname="testCases.firstTest" name="second" time="0.004">
    <skipped/>
  </testcase> <!-- second -->
  <testcase classname="testCases.firstTest" name="second" time="0.0">
    <skipped/>
  </testcase> <!-- second -->
  <testcase classname="testCases.firstTest" name="second" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at testCases.firstTest.second(firstTest.java:17)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- second -->
  <testcase classname="testCases.firstTest" name="first" time="0.0">
    <ignored/>
  </testcase> <!-- first -->
</testsuite> <!-- Surefire test -->
